#!/bin/sh -ef

# publish: publishes build results to a certain repository.
#
# Copyright (C) 2016-2018 Kaitai Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

GH_USER=kaitai-io
GH_REPO_NAME=formats-kaitai-io.github.io
# NB: trailing slash is *very* important for rsync!
OUT_DIR=_build/html/

export GIT_AUTHOR_NAME='Kaitai Bot'
export GIT_AUTHOR_EMAIL='kaitai-bot@kaitai.io'
export GIT_COMMITTER_NAME='Kaitai Bot'
export GIT_COMMITTER_EMAIL='kaitai-bot@kaitai.io'

if [ -z "$BOT_SSH_KEY" ]; then
	echo "BOT_SSH_KEY is not set!"
	exit 1
fi

unset SSH_AGENT_PID SSH_AUTH_SOCK

echo -n 'Setting up bot key... '
echo "$BOT_SSH_KEY" | base64 -d >$HOME/bot_id
chmod 600 $HOME/bot_id
echo OK

echo -n 'Checking if key looks valid... '
key_head=$(head -n1 $HOME/bot_id)
if [ "$key_head" != '-----BEGIN RSA PRIVATE KEY-----' ]; then
	echo 'Nope, key seems to be invalid'
	exit 1
fi
echo -n 'OK, '
sha1sum $HOME/bot_id

# Alas, it seems that Travis CI uses ancient git that doesn't support this
#export GIT_SSH_COMMAND="ssh -i $HOME/bot_id"

# Squelch long git push strategy explanations
git config --global push.default simple

echo -n 'Setting up ssh wrapper... '
cat >$HOME/git-ssh <<__EOF__
#!/bin/sh -ef
ssh -i "$HOME/bot_id" "\$@"
__EOF__
chmod a+x $HOME/git-ssh
export GIT_SSH="$HOME/git-ssh"
echo 'OK'

echo -n 'Setting up github.com ssh known_hosts... '
mkdir -p "$HOME/.ssh"
cat >>$HOME/.ssh/known_hosts <<__EOF__
|1|36IaOOa9TjQvuTuyPPZVLs+wNnI=|FcXQrYSP/WwU/XZJgkHXqWgHHvc= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
|1|fMSJevPd24vwCx/Y5sYhkl7Dh98=|8Dx75sSuPqyGgXLYKmQK+GvGfJA= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
__EOF__
chmod 0700 "$HOME/.ssh"
chmod 0600 "$HOME/.ssh/known_hosts"
echo 'OK'

echo 'Cloning website repo...'
git clone git@github.com:"$GH_USER"/"$GH_REPO_NAME".git

echo 'Updating the files...'
rsync --delete-after -c --exclude=.git --exclude=.travis.yml --exclude=CNAME -r -v "$OUT_DIR" "$GH_REPO_NAME"

cd "$GH_REPO_NAME"

echo 'Adding and committing...'
git add --all .
git commit -m Regen || :

echo 'Pushing...'
git push

echo -n 'Cleaning up the key and wrapper... '
rm "$HOME/bot_id" "$HOME/git-ssh"
echo OK
