#!/bin/sh -e

KSY_DIR=..

for VERSION in 0.8 latest; do
	echo "Building all targets for ksc $VERSION..."
	./build-target "$VERSION" "$KSY_DIR" "target/$VERSION"
done

./check-errors target/*/log.json
./build-diagrams target html
./build-html "$KSY_DIR" target html
